<?php

namespace LabelTools\PhpCwrExporter\Enums;

enum SocietyCode: int
{
    case DP = 0;
    case ACUM = 1;
    case ADDAF = 2;
    case AEPI = 3;
    case AGADU = 4;
    case AKM = 5;
    case BUCUDA = 6;
    case APDAYC = 7;
    case APRA = 8;
    case ARTISJUS = 9;
    case ASCAP = 10;
    case AUSTRO_MECHANA = 11;
    case AMCOS = 12;
    case AWA = 13;
    case ARGENTORES = 14;
    case APA = 15;
    case BUMDA = 16;
    case AMRA = 17;
    case BGDA = 18;
    case BMDA = 19;
    case SODRAC = 20;
    case BMI = 21;
    case MCSN = 22;
    case BUMA = 23;
    case BURIDA = 24;
    case BSDA = 25;
    case CASH = 26;
    case CAPAC = 27;
    case LITA = 28;
    case SCD = 29;
    case AMAR = 30;
    case DILIA = 31;
    case FILSCAP = 32;
    case OMDA = 33;
    case HARRY_FOX_AGENCY = 34;
    case GEMA = 35;
    case IPRS = 36;
    case BUBEDRA = 37;
    case JASRAC = 38;
    case MUSICAUTOR = 39;
    case KODA = 40;
    case LITERAR_MECHANA = 41;
    case LVG = 42;
    case MCSK = 43;
    case MCPS = 44;
    case BBDA = 45;
    case MRS = 46;
    case BCDA = 47;
    case NCB = 48;
    case ONDA = 49;
    case OSA = 50;
    case PROLITTERIS = 51;
    case PRS = 52;
    case PROCAN = 53;
    case ALCS = 54;
    case SABAM = 55;
    case SACD = 56;
    case SACERAU = 57;
    case SACEM = 58;
    case SACM = 59;
    case SACVEN = 60;
    case SADAIC = 61;
    case SADEMBRA = 62;
    case SAMRO = 63;
    case SOKOJ = 64;
    case SAYCE = 65;
    case SBACEM = 66;
    case SBAT = 67;
    case SDRM = 68;
    case SPA = 69;
    case SOGEM = 70;
    case SESAC = 71;
    case SGAE = 72;
    case SCAM = 73;
    case SIAE = 74;
    case SUISSIMAGE = 75;
    case ACEMLA = 76;
    case STEF = 77;
    case STEMRA = 78;
    case STIM = 79;
    case SUISA = 80;
    case SARRAL = 81;
    case OTPDA = 82;
    case SONECA = 83;
    case SAYCO = 84;
    case SOZA = 85;
    case SICAM = 86;
    case SPACEMF = 87;
    case CMRRA = 88;
    case TEOSTO = 89;
    case TONO = 90;
    case SSA = 91;
    case SOCINADA = 92;
    case UBC = 93;
    case RAO = 94;
    case VG_WORT = 95;
    case COTT = 96;
    case ZAIKS = 97;
    case ZIMRA = 98;
    case NS = 99;
    case SOCAN = 101;
    case NASCAM = 102;
    case ACDAM = 103;
    case MACP = 104;
    case MASA = 105;
    case COMPASS = 106;
    case ACAM = 107;
    case CHA = 108;
    case KCI = 109;
    case LATGA_A = 110;
    case HDS_ZAMP = 111;
    case SAZAS = 112;
    case LAA = 113;
    case AGAYC = 114;
    case UCMR_ADA = 115;
    case EAU = 116;
    case MESAM = 117;
    case KOMCA = 118;
    case MCSC = 119;
    case LIRA = 120;
    case VDFS = 121;
    case AKKA_LAA = 122;
    case COSGA = 123;
    case COSOMA = 124;
    case BNDA = 125;
    case MCT = 126;
    case ALBAUTOR = 127;
    case IMRO = 128;
    case SOBODAYCOM = 129;
    case BUTODRA = 130;
    case SADA = 131;
    case BILD_KUNST = 132;
    case ZAMCOPS = 133;
    case SLPRS = 134;
    case SADH = 135;
    case ZAMP = 136;
    case SOFAM = 137;
    case KOPIOSTO = 138;
    case COPY_DAN_BILLEDKUNST = 139;
    case UACRR = 140;
    case ATN_GESATCH = 141;
    case DALRO = 142;
    case TEATERAUTOR = 143;
    case HAA = 144;
    case DPRS = 145;
    case SPAC = 146;
    case FILMAUTOR = 147;
    case ADAGP = 148;
    case ARS = 149;
    case BEELDRECHT = 150;
    case BONO = 151;
    case BUS = 152;
    case DACS = 153;
    case HUNGART = 154;
    case SOMAAP = 155;
    case VAGA = 156;
    case VBK = 157;
    case VEGAP = 158;
    case VISCOPY = 159;
    case RUPIS = 160;
    case MUST = 161;
    case AMPAL = 162;
    case APG_JAPAN = 163;
    case APSAV = 164;
    case ATN = 165;
    case AUTORARTE = 166;
    case BURAFO = 167;
    case CAL = 168;
    case COSCAP = 169;
    case CPSN = 170;
    case CREAIMAGEN = 171;
    case DGA = 172;
    case DIRECTORES = 173;
    case FLIM_JUS = 174;
    case COPYRO = 175;
    case JACAP = 176;
    case KAZAK = 177;
    case KOSA = 178;
    case KUVASTO = 179;
    case MUSIKEDITION = 180;
    case NMPA = 181;
    case PAPPRI = 182;
    case SACK = 183;
    case SARTEC = 184;
    case SESAM = 185;
    case SGDL = 186;
    case SNAC = 187;
    case SOCIETE_DE_L_IMAGE = 188;
    case SOCINPRO = 189;
    case SOPE = 190;
    case SPACQ = 191;
    case SFF = 192;
    case THE_SOCIETY_OF_AUTHORS = 193;
    case UFFICIO_LEGALE = 194;
    case VEVAM = 195;
    case WGA = 196;
    case WGJ = 197;
    case ZAPA = 199;
    case MSG = 200;
    case ABRAMUS = 201;
    case ASDAC = 202;
    case AWGACS = 203;
    case SAS = 204;
    case SODART = 205;
    case SUOMEN_KIRJAILIJALIITTO = 206;
    case THE_AUTHORS_REGISTRY_INC = 207;
    case SGA = 208;
    case ARMAUTHOR = 209;
    case ACCESS = 210;
    case NO_LONGER_IN_USE = 211;
    case CSCS = 212;
    case DRCC = 213;
    case HMS = 214;
    case KYRGYZPATENT = 215;
    case SQN = 216;
    case ABRAC = 217;
    case ANACIM = 218;
    case ASSIM = 219;
    case ATIDA = 220;
    case SABEM = 221;
    case FONOPERU = 222;
    case COSOTA = 223;
    case SOMAS = 224;
    case SAIF = 225;
    case AACIMH = 226;
    case SGACEDOM = 227;
    case ROMS = 228;
    case ICG = 229;
    case ADAVIS = 230;
    case AUTVIS = 231;
    case GESTOR = 232;
    case SACEMLUXEMBOURG = 233;
    case UCOSO = 234;
    case SACENC = 235;
    case WID_CENTRE = 300;
    case GESAC = 301;
    case LATINAUTOR = 302;
    case NORD_DOC = 303;
    case SONGCODE = 304;
    case IMJV = 305;
    case CCL = 306;
    case MISASIA = 307;
    case ECAD = 308;
    case LATINNET = 309;
    case DIVA = 310;

    private const NAMES = [
        0 => 'DP - Public Domain',
        1 => 'ACUM - Israel',
        2 => 'ADDAF - Brazil',
        3 => 'AEPI - Greece',
        4 => 'AGADU - Uruguay',
        5 => 'AKM - Austria',
        6 => 'BUCUDA - Central Afr Rep',
        7 => 'APDAYC - Peru',
        8 => 'APRA - Australia',
        9 => 'ARTISJUS - Hungary',
        10 => 'ASCAP - United States',
        11 => 'AUSTRO-MECHANA - Austria',
        12 => 'AMCOS - Australia',
        13 => 'AWA - German Dem Rep',
        14 => 'ARGENTORES - Argentina',
        15 => 'APA - Paraguay',
        16 => 'BUMDA - Mali',
        17 => 'AMRA - United States',
        18 => 'BGDA - Guinea',
        19 => 'BMDA - Morocco',
        20 => 'SODRAC - Canada',
        21 => 'BMI - United States',
        22 => 'MCSN - Nigeria',
        23 => 'BUMA - Netherlands',
        24 => 'BURIDA - Ivory Coast',
        25 => 'BSDA - Senegal',
        26 => 'CASH - Hong Kong',
        27 => 'CAPAC - Canada',
        28 => 'LITA - Slovakia',
        29 => 'SCD - Chile',
        30 => 'AMAR - Brazil',
        31 => 'DILIA - Czech Republic',
        32 => 'FILSCAP - Philippines',
        33 => 'OMDA - Madagascar',
        34 => 'HARRY FOX AGENCY - United States',
        35 => 'GEMA - German Fed Rep',
        36 => 'IPRS - India',
        37 => 'BUBEDRA - Benin',
        38 => 'JASRAC - Japan',
        39 => 'MUSICAUTOR - Bulgaria',
        40 => 'KODA - Denmark',
        41 => 'LITERAR-MECHANA - Austria',
        42 => 'LVG - Austria',
        43 => 'MCSK - Kenya',
        44 => 'MCPS - United Kingdom',
        45 => 'BBDA - Burkina Faso',
        46 => 'MRS - United Kingdom',
        47 => 'BCDA - Congo',
        48 => 'NCB - Scandinavia',
        49 => 'ONDA - Algeria',
        50 => 'OSA - Czech Republic',
        51 => 'PROLITTERIS - Switzerland',
        52 => 'PRS - United Kingdom',
        53 => 'PROCAN - Canada',
        54 => 'ALCS - United Kingdom',
        55 => 'SABAM - Belgium',
        56 => 'SACD - France',
        57 => 'SACERAU - Egypt',
        58 => 'SACEM - France',
        59 => 'SACM - Mexico',
        60 => 'SACVEN - Venezuela',
        61 => 'SADAIC - Argentina',
        62 => 'SADEMBRA - Brazil',
        63 => 'SAMRO - South Africa',
        64 => 'SOKOJ - Yugoslavia',
        65 => 'SAYCE - Ecuador',
        66 => 'SBACEM - Brazil',
        67 => 'SBAT - Brazil',
        68 => 'SDRM - France (use SACEM instead)',
        69 => 'SPA - Portugal',
        70 => 'SOGEM - Mexico',
        71 => 'SESAC - United States',
        72 => 'SGAE - Spain',
        73 => 'SCAM - France',
        74 => 'SIAE - Italy',
        75 => 'SUISSIMAGE - Switzerland',
        76 => 'ACEMLA - Puerto Rico',
        77 => 'STEF - Iceland',
        78 => 'STEMRA - Netherlands',
        79 => 'STIM - Sweden',
        80 => 'SUISA - Switzerland',
        81 => 'SARRAL - South Africa',
        82 => 'OTPDA - Tunisia',
        83 => 'SONECA - Zaire',
        84 => 'SAYCO - Columbia',
        85 => 'SOZA - Slovakia',
        86 => 'SICAM - Brazil',
        87 => 'SPACEMF - French Polynesia',
        88 => 'CMRRA - Canada',
        89 => 'TEOSTO - Finland',
        90 => 'TONO - Norway',
        91 => 'SSA - Switzerland',
        92 => 'SOCINADA - Cameroon Rep',
        93 => 'UBC - Brazil',
        94 => 'RAO - Russia',
        95 => 'VG WORT - Germany',
        96 => 'COTT - Trinidad & Tobago',
        97 => 'ZAIKS - Poland',
        98 => 'ZIMRA - Zimbabwe',
        99 => 'NS -',
        101 => 'SOCAN - Canada',
        102 => 'NASCAM - Namibia',
        103 => 'ACDAM - Cuba',
        104 => 'MACP - Malaysia',
        105 => 'MASA - Mauritius',
        106 => 'COMPASS - Singapore',
        107 => 'ACAM - Costa Rica',
        108 => 'CHA - Taiwan',
        109 => 'KCI - Indonesia',
        110 => 'LATGA-A - Lithuania',
        111 => 'HDS-ZAMP - Croatia',
        112 => 'SAZAS - Slovenia',
        113 => 'LAA - Latvia',
        114 => 'AGAYC - Guatemala',
        115 => 'UCMR-ADA - Romania',
        116 => 'EAU - Estonia',
        117 => 'MESAM - Turkey',
        118 => 'KOMCA - South Korea',
        119 => 'MCSC - China',
        120 => 'LIRA - Netherlands',
        121 => 'VDFS - Austria',
        122 => 'AKKA/LAA - Latvia',
        123 => 'COSGA - Ghana',
        124 => 'COSOMA - Malawi',
        125 => 'BNDA - Niger',
        126 => 'MCT - Thailand',
        127 => 'ALBAUTOR - Albania',
        128 => 'IMRO - Ireland',
        129 => 'SOBODAYCOM - Bolivia',
        130 => 'BUTODRA - Togo',
        131 => 'SADA - Greece',
        132 => 'BILD-KUNST - German Federal Republic',
        133 => 'ZAMCOPS - Zambia',
        134 => 'SLPRS - Sri Lanka',
        135 => 'SADH - Greece',
        136 => 'ZAMP - Macedonia',
        137 => 'SOFAM - Belgium',
        138 => 'KOPIOSTO - Finland',
        139 => 'COPY-DAN BILLEDKUNST - Denmark',
        140 => 'UACRR - Ukraine',
        141 => 'ATN (formerly GESATCH) - Chile',
        142 => 'DALRO - South Africa',
        143 => 'TEATERAUTOR - Bulgaria',
        144 => 'HAA - Croatia',
        145 => 'DPRS - United Kingdom',
        146 => 'SPAC - Panama',
        147 => 'FILMAUTOR - Bulgaria',
        148 => 'ADAGP - France',
        149 => 'ARS - United States',
        150 => 'BEELDRECHT - Netherlands',
        151 => 'BONO - Norway',
        152 => 'BUS - Sweden',
        153 => 'DACS - United Kingdom',
        154 => 'HUNGART - Hungary',
        155 => 'SOMAAP - Mexico',
        156 => 'VAGA - United States',
        157 => 'VBK - Austria',
        158 => 'VEGAP - Spain',
        159 => 'VISCOPY - Australia',
        160 => 'RUPIS - Belarus',
        161 => 'MUST - Taiwan (Province Of China)',
        162 => 'AMPAL - Australia',
        163 => 'APG-JAPAN - Japan',
        164 => 'APSAV - Peru',
        165 => 'ATN - Chile',
        166 => 'AUTORARTE - Venezuela',
        167 => 'BURAFO - Netherlands',
        168 => 'CAL - Australia',
        169 => 'COSCAP - Barbados',
        170 => 'CPSN - Nepal',
        171 => 'CREAIMAGEN - Chile',
        172 => 'DGA - United States',
        173 => 'DIRECTORES - Mexico',
        174 => 'FLIM JUS - Hungary',
        175 => 'COPYRO - Romania',
        176 => 'JACAP - Jamaica',
        177 => 'KAZAK - Kazakhstan',
        178 => 'KOSA - Korea Republic Of',
        179 => 'KUVASTO - Finland',
        180 => 'MUSIKEDITION - Austria',
        181 => 'NMPA - United States',
        182 => 'PAPPRI - Indonesia',
        183 => 'SACK - Korea Republic Of',
        184 => 'SARTEC - Canada',
        185 => 'SESAM - France',
        186 => 'SGDL - France',
        187 => 'SNAC - France',
        188 => 'SOCIETE DE L’IMAGE - France',
        189 => 'SOCINPRO - Brazil',
        190 => 'SOPE - Greece',
        191 => 'SPACQ - Canada',
        192 => 'SFF - Sweden',
        193 => 'THE SOCIETY OF AUTHORS - United Kingdom',
        194 => 'UFFICIO LEGALE - Holy See (Vatican City State)',
        195 => 'VEVAM - Netherlands',
        196 => 'WGA - United States',
        197 => 'WGJ - Japan',
        198 => 'ZAMP - Slovenia',
        199 => 'ZAPA - Poland',
        200 => 'MSG - Turkey',
        201 => 'ABRAMUS - Brazil',
        202 => 'ASDAC - Moldova - Republic Of',
        203 => 'AWGACS - Australia',
        204 => 'SAS - Georgia',
        205 => 'SODART - Canada',
        206 => 'SUOMEN KIRJAILIJALIITTO - Finland',
        207 => 'THE AUTHOR\'S REGISTRY INC. - United States',
        208 => 'SGA - Guinea-Bissau',
        209 => 'ARMAUTHOR - Armenia',
        210 => 'ACCESS - Canada (Formerly CANCOPY)',
        211 => 'No Longer In Use',
        212 => 'CSCS - Canada',
        213 => 'DRCC - Canada',
        214 => 'HMS - Saint Lucia',
        215 => 'KYRGYZPATENT - Kyrgyzstan',
        216 => 'SQN - Bosnia And Herzegovina',
        217 => 'ABRAC - Brazil',
        218 => 'ANACIM - Brazil',
        219 => 'ASSIM - Brazil',
        220 => 'ATIDA - Brazil',
        221 => 'SABEM - Brazil',
        222 => 'FONOPERU - Peru',
        223 => 'COSOTA - Tanzania, United Republic Of',
        224 => 'SOMAS - Mozambique',
        225 => 'SAIF - France',
        226 => 'AACIMH - Honduras',
        227 => 'SGACEDOM - Dominican Republic',
        228 => 'ROMS - Russian Federation',
        229 => 'ICG - United States',
        230 => 'ADAVIS - Cuba',
        231 => 'AUTVIS - Brazil',
        232 => 'GESTOR - Czech Republic',
        233 => 'SACEMLUXEMBOURG - Luxembourg',
        234 => 'UCOSO - Uganda',
        235 => 'SACENC - France',
        300 => 'WID CENTRE - United States',
        301 => 'GESAC - Belgium',
        302 => 'LATINAUTOR - Uruguay',
        303 => 'NORD-DOC - Sweden',
        304 => 'SONGCODE - United States',
        305 => 'IMJV - Netherlands',
        306 => 'CCL - Trinidad And Tobago',
        307 => 'MISASIA - Singapore',
        308 => 'ECAD - Brazil',
        309 => 'LATINNET - Spain',
        310 => 'DIVA - Hong Kong',
    ];

    public function getName(): string
    {
        return self::NAMES[$this->value] ?? '';
    }

    /**
     * Returns the country/territory for this society code.
     */
    public function getTerritory(): string
    {
        // Split the stored "CODE - Territory" string and return the Territory part
        $full = self::NAMES[$this->value] ?? '';
        $parts = explode(' - ', $full, 2);
        return $parts[1] ?? '';
    }
}
